/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 laptop.gltf --transform
Author: Özlem Çandır (https://sketchfab.com/OzlemCandir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gamer-laptop-editable-display-faa3d29ff5404b509f308f391b70d3e0
Title: Gamer Laptop (Editable Display)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/laptop-transformed.glb')
  return (
    <group {...props} dispose={null} scale={0.03}>
      <group scale={0.01}>
        <group position={[184.9, -140, 217.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder003_Laptop_0.geometry} material={materials.Laptop} />
          <mesh geometry={nodes.Cylinder003_Laptop001_0.geometry} material={materials['Laptop.001']}>
          <meshStandardMaterial
          color="#000"
          envMapIntensity={0.8}
          />
        </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/laptop-transformed.glb')
