/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 moon.gltf --transform
Author: Bastien Genbrugge (https://sketchfab.com/bastienBGR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-orbiting-moon-c613bee6fbd041e58a35d777ae87bdcb
Title: Rocket Orbiting Moon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/moon-transformed.glb')
  return (
    <group {...props} dispose={null} scale={2}>
      <mesh geometry={nodes.Ring_1_Ring_0.geometry} material={materials.Ring} position={[-160.7, 8.56, 70.84]} rotation={[-1.55, -0.88, 2.54]} scale={1.02} />
      <mesh geometry={nodes.Raket_1_Raket_0.geometry} material={materials.Raket} position={[0, -59.29, 0]} rotation={[0, 1.24, 0]} />
      <mesh geometry={nodes.Subdivision_Surface_Subdivision_Surface1_0.geometry} material={materials['Subdivision_Surface.1']} position={[6.23, 27.45, 6.83]} rotation={[0.02, -0.11, -2.16]} />
    </group>
  )
}

useGLTF.preload('/moon-transformed.glb')
