/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 nike.gltf --transform
Author: MamaTeeku (https://sketchfab.com/MamaTeeku)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-shoe-d796cf8784fc46169e3ac70375e0e8a8
Title: Nike Shoe
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'
import * as THREE from "three"

export default function Model(props) {
  const { nodes, materials } = useGLTF('/nike-transformed.glb')
  return (
    <group {...props} dispose={null} scale={0.47}>
      <group scale={0.3}>
        <mesh geometry={nodes.RT_AirMax90_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[8, -4, 0.3]}>
          <meshStandardMaterial
          color="#ca7505"
          envMapIntensity={0.8}
          />
        </mesh>
        <mesh geometry={nodes.RT_AirMax90_aiStandardSurface1_0_1.geometry} material={materials.aiStandardSurface1}  position={[8, -4, 0.3]}>
        <meshStandardMaterial
          color="orange"
          envMapIntensity={0.8}
          />
          </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/nike-transformed.glb')
